version: '2'
services:
    shoppinglist-app:
        image: shoppinglist
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://shoppinglist-mysql:3306/shoppinglist?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shoppinglist-mysql:
        extends:
            file: mysql.yml
            service: shoppinglist-mysql
